# Generated by Django 5.1 on 2024-08-15 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('ID_cv', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prenom', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='cv_documents/')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departement.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('idP', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.DateField()),
                ('statut', models.CharField(choices=[('congé', 'Congé'), ('absent', 'Absent'), ('présent', 'Présent')], max_length=10)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departement.departement')),
            ],
        ),
    ]
