# Generated by Django 5.1 on 2024-08-16 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_Employe', '0002_initial'),
        ('personne', '0004_alter_pointeur_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('Idc', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('document', models.FileField(upload_to='conge_documents/')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personne.employe')),
            ],
        ),
    ]
