# Generated by Django 5.1 on 2024-08-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departement', '0001_initial'),
        ('gestion_Employe', '0003_conge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pointage',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_Employe.listestatut'),
        ),
        migrations.CreateModel(
            name='Point_PDF',
            fields=[
                ('idPD', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.DateField()),
                ('P_PDF', models.FileField(upload_to='pdf_pointage/')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departement.departement')),
            ],
        ),
    ]
