# Generated by Django 5.1 on 2024-08-29 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_Employe', '0005_cv_adresse_cv_date_depot_cv_date_naissance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conge',
            name='document',
        ),
        migrations.AddField(
            model_name='conge',
            name='date_demande',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conge',
            name='reference',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
