# Generated by Django 5.1 on 2024-08-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_Employe', '0008_alter_conge_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
