# Generated by Django 5.1 on 2024-08-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_Employe', '0009_alter_conge_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conge',
            name='reference',
        ),
    ]
