# Generated by Django 5.1 on 2024-08-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_Employe', '0010_remove_conge_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
