# Generated by Django 5.1 on 2024-08-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_Employe', '0011_conge_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
