# Generated by Django 5.1 on 2024-08-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointeur',
            name='email',
            field=models.EmailField(default='exit', max_length=254),
            preserve_default=False,
        ),
    ]
