# Generated by Django 5.1 on 2024-08-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0003_alter_pointeur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointeur',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
