# Generated by Django 5.1 on 2024-08-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id_Dep', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('numero_telephone', models.CharField(max_length=15)),
            ],
        ),
    ]
